routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('email', function() {

//     return new App\Mail\LoginCredentials(App\User::first(), 'asd123');
// });


Route::get('/', 'PagesController@home')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');
Route::get('staticpage', 'StaticPage@show')->name('staticpage.show');



Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');


Route::get('login/{socialNetwork}', 'SocialLoginController@redirectToSocialNetwork')->name('login.social')->middleware('guest');
Route::get('login/{SocialNetwork}/callback', 'SocialLoginController@handleSocialNetworkCallback')->middleware('guest');

//Métodos con el prefijo Admin

Route::group(['prefix' => 'admin', 
    'namespace' => 'Admin', 
    'middleware' => 'auth'], 
    function() {
        //rutas de administración
    Route::get('/','AdminController@index')->name('dashboard');


    Route::resource('media', 'MediaController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('condos', 'CondosController', ['except' => '', 'as' => 'admin']);
    Route::resource('properties', 'PropertiesController', ['except' => '', 'as' => 'admin']);
    Route::resource('debts', 'DebtsController', ['except' => '', 'as' => 'admin']);
    Route::resource('members', 'MembersController', ['except' => '', 'as' => 'admin']);
    Route::resource('visitors', 'VisitorsController', ['except' => '', 'as' => 'admin']);  
    Route::resource('payments', 'PaymentsController', ['except' => '', 'as' => 'admin']);          
    Route::resource('incidents', 'IncidentsController', ['except' => '', 'as' => 'admin']);
    Route::resource('reservations', 'ReservationsController', ['except' => '', 'as' => 'admin']);
    Route::resource('events', 'EventsController', ['except' => '', 'as' => 'admin']);
    Route::resource('commonareas', 'CommonAreasController', ['except' => '', 'as' => 'admin']);
    Route::resource('visits', 'VisitsController', ['except' => '', 'as' => 'admin']);
    Route::resource('listings', 'ListingsController', ['except' => '', 'as' => 'admin']);
    Route::resource('divisions', 'DivisionsController', ['except' => '', 'as' => 'admin']);
    Route::resource('subdivisions', 'SubdivisionsController', ['except' => '', 'as' => 'admin']);
    Route::resource('services', 'ServicesController', ['except' => '', 'as' => 'admin']);

    Route::get('listings.categories', 'ListingsController@categories')->name('admin.listings.categories');
    Route::get('listings.subcategories', 'ListingsController@subcategories')->name('admin.listings.subcategories');
    Route::get('listings.listings', 'ListingsController@listings')->name('admin.listings.listings');




    Route::resource('contacts', 'ContactController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('page', 'PageController', ['except' => '', 'as' => 'admin']);
    Route::resource('projects', 'ProjectController', ['except' => 'show', 'as' => 'admin']);
    Route::get('procjects/goback', 'ProjectController@goback')->name('admin.projects.goback');


    Route::resource('setting', 'SettingController', ['except' => '', 'as' => 'admin']);
    Route::resource('posts', 'PostsController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController', [ 'as' => 'admin']);
    Route::resource('roles', 'RolesController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update'], 'as' => 'admin']);

    Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('admin.users.roles.update');

    Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionController@update')->name('admin.users.permissions.update');


    Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');     
    Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');

    Route::post('projects/{project}/projectphotos', 'ProjectPhotosController@store')->name('admin.projectphotos.projectphotos.store'); 

    Route::post('projects/{project}/projectheader', 'ProjectPhotosController@header')->name('admin.projectphotos.projectphotos.header'); 

    Route::delete('projectphotos/{projectphoto}', 'ProjectPhotosController@destroy')->name('admin.projectphotos.destroy');     

    Route::post('condos/{condo}/condologos', 'CondosLogosController@store')->name('admin.condos.condologos.store');

    Route::delete('condologos/{condologo}', 'CondosLogosController@destroy')->name('admin.condologos.destroy');
 
    Route::post('condos/{condo}/condophotos', 'CondosPhotosController@store')->name('admin.condos.condophotos.store');

    Route::delete('condophotos/{condophoto}', 'CondosPhotosController@destroy')->name('admin.condophotos.destroy');

});





//Quitar para desactivar registro
Auth::routes();
        // Authentication Routes...
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

app/Visitor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Visitor extends Model
{

	
	protected $guarded = [];
	public function property(){

		return $this->belongsTo(Property::class);

	}
}

app/Http/Controllers/Admin/VisitorsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Visitor;
use App\Property;

class VisitorsController extends Controller
{
    public function index () {

    	$properties = Property::all();
        $visitors = Visitor::orderBy('id', 'desc')->get();;
    	return view('admin.visitors.index', compact('visitors', 'properties'));
    }

        public function show (Property $property) {
		return view('admin.visitors.show', compact('visitors'));
    }



       public function store(Request $request) {

        $this->validate($request,[
        'name' => 'required',
        'property_id' => 'required',
        'next_visit' => 'required',
    ]);
        $visitor = Visitor::create($request->all());
        $visitor->ine_url = '/img/user.png';
        return redirect()->route('admin.visitors.index')->with('flash', 'El Visitante Fue Creado Correctamente');

    }     

        public function destroy(Listing $visitor){
        
        $visitor->delete();
         return redirect()->route('admin.visitors.index')->with('flash', 'El Visitante ha sido Eliminado');

    }
}

resources/views/admin/visitors/index.blade.php
@extends('admin.layout')
@section('header')
      <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Visitantes</h1>
            <small>Listado</small>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Inicio</a></li>
              <li class="breadcrumb-item active">Visitantes</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
@stop
@section('content')

<div class="row mb-2">       
  <div class="col-sm-4">
    <div class="card card-primary">
      <div class="card-header">
      </div>         
        <div class="card-body">

<form method="POST" action="{{route('admin.visitors.store')}}">
      {{csrf_field()}}

  <h4>Crear Visitante</h4>



     <div class="form-group">    
   <label>Nombre</label>
                <input name="name" 
                class="form-control" 
                placeholder="Ingresa el Nombre" 
                value="">
                </input>
            </div>

                <div class="form-group">      
                  <label>Vivienda que visitará</label>
                  <select name="property_id" class="form-control select2">
                    <option value=""> 
                      Selecciona Una Vivienda
                    </option>
                    @forelse($properties as $property)
                    <option value="{{$property->id}}">{{$property->address}}
                      </option>
                    @empty
                    @endforelse
                  </select>
                </div>
                  


                  <label>Próxima visita:</label>

                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="far fa-calendar-alt"></i>
                      </span>
                    </div>
                    <input name="next_visit" 
                    type="text" 
                    class="form-control float-right" 
                    id="datepicker" 
                    value="{{Carbon\Carbon::now()->format('m/d/Y')}}">
                  </div>
                  <!-- /.input group -->
             



                <br>
                <div class="form-group">                
                <button type="submit" class="btn btn-primary btn-block">
                  Crear Visitante
                </button>
                </div>
               {!!$errors->first('name', ' <span class="help-block" style= "color:red;">:message</span>')!!}
                      </div>

                <div class="form-group {{$errors->has('name') ? 'is-invalid' : ''}}">
                </div>

          </form>

          </div>
      </div>


<div class="col-sm-8">
    <div class="card card-primary">
      <div class="card-header">
      </div>         
          <div class="card-body">
              <table id="posts-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Nombre</th>
                  <th>Vivienda</th>
                  <th>Condominio</th>                              
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                  @forelse($visitors as $visitor)
               <tr>
                 <td>{{$visitor->id}}</td>
                  <td>{{$visitor->name}}</td>
                  <td>
                    {{ $visitor->property->address }}
                  </td>

                  <td>{{ $visitor->property->condo->name }}</td>
     
                  <td>

                    <a class="btn btn-default btn-sm" href="{{route('admin.visitors.show', $visitor)}}" target="_blank"><i class="fas fa-eye"></i></a>
                    <a class="btn btn-info btn-sm" href="{{route('admin.visitors.edit', $visitor)}}"><i class="fas fa-pencil-alt"></i></a>
                    <form method="POST" action="{{route('admin.visitors.destroy', $visitor)}}" style="display: inline;"> 
                      {{ csrf_field() }} {{method_field('DELETE')}}
                      
                    <button class="btn btn-danger btn-sm" href="" onclick="return confirm('Estás Seguro de Querer Eliminar Esta Publicación?')"><i class="fas fa-times"></i></button>

                    </form>
                      

                  </td>

                   </tr>
                  @empty
                  <tr>
                    <td>No hay datos para mostrar</td>
                  </tr>
                  @endforelse
                </tbody>

              </table>
            </div>
            <!-- /.card-body -->
          </div>
@endsection


@push('styles')
    <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/dropzone.css">
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- daterange picker -->
  <link rel="stylesheet" href="/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/plugins/select2/css/select2.min.css">
  <link rel="stylesheet" href="/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
@endpush

@push('scripts')

<!-- DataTables -->
<script src="/adminlte/plugins/datatables/jquery.dataTables.js"></script>
<script src="/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/min/dropzone.min.js"></script>
<!-- Select2 -->
<script src="/adminlte/plugins/select2/js/select2.full.min.js"></script>
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<!-- bootstrap datepicker -->
<script src="/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>


<script>
  $(function () {
    $("#example1").DataTable();
    $('#posts-table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": false,
      "info": true,
      "autoWidth": false,
    });
  });
</script>

<script>
    //Date picker
    $('#datepicker').datepicker({
      autoclose: true
    })
</script>
<script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1')
    CKEDITOR.config.height = 355;
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>
<script>

    $(function () {
    //Initialize Select2 Elements
    $('.select2').select2({

      tags:true
    })

    //Initialize Select2 Elements
    $('.select2bs4').select2({

      tags:true
    })
  });
</script>

@endpush